# SPDX-FileCopyrightText: 2024 Margo
#
# SPDX-License-Identifier: MIT
#
# Author: Christian Storm <christian.storm@siemens.com>
# Author: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>
---
name: GitHub Pages

on:
  push:
    branches:
      - pre-draft
      - specification_use-linkml

permissions:
  contents: write

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install poetry
        run: pipx install poetry
    
      - name: Check pyproject.toml and poetry.lock
        run: poetry check

  validate:
    needs:
      - quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tags if not run from main repo
        if: github.repository != 'margo/specification'
        run: |
          git remote add upstream https://github.com/margo/specification
          git fetch upstream --tags

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction --all-extras

      - name: Run tests
        run: |
          doc-generation/check-examples.bash

  documents:
    needs:
      - quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tags if not run from main repo
        if: github.repository != 'margo/specification'
        run: |
          git remote add upstream https://github.com/margo/specification
          git fetch upstream --tags

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction --all-extras

      - name: Generate MarkDown documentation
        run: |
          doc-generation/generate-documentation.bash

      - name: Share generated documentation with later jobs
        uses: actions/upload-artifact@v4
        with:
          name: desired-state.md
          path: system-design/margo-api-reference/workload-api/desired-state-api/desired-state.md

  pages:
    needs:
      - validate
      - documents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Prime Cache Key
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install mkdocs-material
        run: pip install mkdocs mkdocs-material mkdocs-markdownextradata-plugin

      - name: Get generated documentation from previous jobs
        uses: actions/download-artifact@v4
        with:
          name: desired-state.md
          path: system-design/margo-api-reference/workload-api/desired-state-api

      - name: GitHub Pages Deploy
        run: mkdocs gh-deploy --force --clean --verbose
